// Generated by ReScript, PLEASE EDIT WITH CARE


function setupSmoothScrolling() {
  document.querySelectorAll("a[href^=\"#\"]").forEach(anchor => {
    anchor.addEventListener("click", event => {
      event.preventDefault();
      let href = anchor.getAttribute("href");
      if (href == null) {
        return;
      }
      let target = document.querySelector(href);
      if (!(target == null)) {
        target.scrollIntoView({
          behavior: "smooth",
          block: "start"
        });
        return;
      }
    });
  });
}

function setupScrollAnimations() {
  let observerOptions = {
    threshold: 0.5,
    rootMargin: "0px 0px -100px 0px"
  };
  let statsObserver = new IntersectionObserver(entries => {
    entries.forEach(entry => {
      if (!entry.isIntersecting) {
        return;
      }
      let target = entry.target;
      target["style.opacity"] = "1";
      target["style.transform"] = "translateY(0)";
    });
  }, observerOptions);
  document.querySelectorAll(".stat-card").forEach(card => {
    card["style.opacity"] = "0";
    card["style.transform"] = "translateY(30px)";
    card["style.transition"] = "all 0.6s ease-out";
    statsObserver.observe(card);
  });
  document.querySelectorAll(".feature").forEach((feature, index) => {
    feature["style.opacity"] = "0";
    feature["style.transform"] = "translateY(30px)";
    feature["style.transition"] = `all 0.6s ease-out ` + (index * 0.1).toString() + `s`;
    let featureObserver = new IntersectionObserver(entries => {
      entries.forEach(entry => {
        if (!entry.isIntersecting) {
          return;
        }
        let target = entry.target;
        target["style.opacity"] = "1";
        target["style.transform"] = "translateY(0)";
      });
    }, observerOptions);
    featureObserver.observe(feature);
  });
}

function trackDemoBotClicks() {
  document.querySelectorAll("a[href*=\"t.me/stamp_demo_bot\"]").forEach(link => {
    link.addEventListener("click", _event => console.log("Demo bot link clicked"));
  });
}

function init() {
  setupSmoothScrolling();
  setupScrollAnimations();
  trackDemoBotClicks();
}

document.addEventListener("DOMContentLoaded", _event => init());

export {
  setupSmoothScrolling,
  setupScrollAnimations,
  trackDemoBotClicks,
  init,
}
/*  Not a pure module */
